olimpiadi-informatica/task-maker-rust

- src/opt.rs
- src/worker.rs
Forking in multithreaded programs is unsafe.
> Make Workers spawn a single thread.

- data/statements/cms-contest.cls
- task-maker-format/src/ioi/statement/statement.rs
It allows to write something like this:
```
$1 \le N \le \limiti{MAXN}$
\begin{itemize}
\item \subtask Examples.
\item \subtask $N \leq \limitist{MAXN}$.
\item \subtask $N \leq \limitist{MAXN}$.
\item \subtask No further constraints.
\end{itemize}
```
\st will be expanded to the current subtask number (1-based), and \limiti will extract the corresponding variable from limiti.py; \limitist will extract subtask[\st]
`gen/GEN` and `gen/limiti.py` will be automatically added to the sandbox of the booklet.
> Add macros to extract information from GEN and limiti.py

- data/statements/cms-contest.cls
Example usage:
```
\begin{signatures}
C++     & \mintinline[breaklines]{c++}{void accendi(int N, int acceso[]);}\\
\midrule
Pascal  & \mintinline[breaklines]{pascal}{procedure accendi(N: longint, var acceso: array of longint)}\\
\end{signatures}
```
> Add an environment for function signatures.

- Cargo.lock
- src/tools/sandbox.rs
- update tabox to version 1.1.0
- update the `task-maker-tools sandbox` command to avoid mounting `/box` on macOS
> Fix compatibility with macOS Monterey

- task-maker-format/src/ioi/format/italian_yaml/mod.rs
MacOS doesn't support statically linked binaries, see https://developer.apple.com/library/archive/qa/qa1118/_index.html
> Fix static compilation on MacOS

- tools/fuzz_checker.sh
Running the fuzzer should allow catching various problems that can arise
during a contest, such as producing negative/weird scores or crashing
(thus failing to evaluate the task).
> Add a script to fuzz the checker of an IOI-style problem.

- Cargo.lock
- task-maker-async/Cargo.toml
- task-maker-async/src/dag.rs
- task-maker-async/src/lib.rs
- task-maker-async/src/server.rs
The async client will create an async-DAG out of a "normal" TMR DAG,
then send it to the server for execution. Once the async code is ready,
the various frontends can be converted to directly create an async-DAG.
> Add async-specific DAG definition.

- Cargo.lock
- task-maker-async/Cargo.toml
- task-maker-async/src/client.rs
- task-maker-async/src/dag.rs
- task-maker-async/src/error.rs
- task-maker-async/src/file_set.rs
- task-maker-async/src/lib.rs
- task-maker-async/src/server.rs
- task-maker-async/src/store.rs
Writing permits are now acquired by calling activate_for_writing, and
cleanup is performed when that RPC is dropped.
As a side effect, this also implements reading of partial files.
> Remove the concept of read handles and leases.

- task-maker-lang/src/languages/cpp.rs
To reproduce create a cpp checker as a symlink and have it include a header which is present in the check directory, but not at the location where the link points to. Because of `std::fs::canonicalize` the symlink will get resolved and the compilation will fail. For example g++ compiles the checker correctly.
> Fix cpp::extract_includes resolving symlinks

- task-maker-lang/src/language.rs
- task-maker-lang/src/languages/rust.rs
When compiling Rust files force the name of the source file to be
source.rs inside the sandbox. This way when there's a grader it can
import the solution module with:
```rust
mod source;
fn main() {
let x = source::thing(42);
}
```
cc: @Virv12 can you try it out and tell me if it works?
Fixes #64
> Fix Rust compilation with graders

- task-maker-format/src/ioi/dag/task_type/communication.rs
- tests/communication_stdio.rs
- tests/tasks/communication_stdio/sol/tle.cpp
Previously, if the solution crashed (or timed out) just after providing
the manager the answer, the solution will get the correct outcome
(TLE/MLE/RE), but the score only comes from the manager (including 1.0).
With this patch the score of the solution is the minimum between the
outcome of a solution (which is either nothing if it exits cleanly, or
0.0 if crashes, times out, ...) and the score provided by the manager.
CC: #63
> Consider communication's solution TLE/MLE/RE for the score

- tools/aur/task-maker-rust-git/PKGBUILD
- tools/aur/task-maker-rust/PKGBUILD
`task-maker-tools` is compiled without the environment variable `TM_DATA_DIR`
> Fix AUR package

- Cargo.lock
- Cargo.toml
- src/opt.rs
- src/tools/booklet.rs
- src/tools/find_bad_case/mod.rs
- task-maker-format/src/detect_format.rs
Enabling [require_equals](
https://docs.rs/clap/latest/clap/builder/struct.Arg.html#method.require_equals) allows syntaxes like this:
```sh
task-maker-rust --no-cache solution.cpp
```
> Improve argument parsing

- src/tools/fuzz_checker.rs
- src/tools/fuzz_checker/checker_header.h
- src/tools/fuzz_checker/fuzzer.cpp
Read TM_CXX_STD_VERSION.
Mark EXIT as [[noreturn]].
> Default fuzz-checker standard to c++17.

- task-maker-format/src/ioi/dag/mod.rs
- task-maker-format/src/ioi/finish_ui.rs
- task-maker-format/src/ioi/format/italian_yaml/mod.rs
- task-maker-format/src/ioi/mod.rs
- task-maker-format/tests/utils.rs
If you don't specify `score_precision` in task.yaml the UI looks pretty much identical (with the same score precision used as before). If you pass it, it will be used in some places, but not everywhere, to keep the UI compact.
Fixes #119
> Read score_precision from task.yaml and use it in the final ui

- src/tools/add_solution_checks.rs
- task-maker-format/src/ioi/ui_state.rs
- task-maker-format/src/solution.rs
Rewrite a good part of solution checks.
We introduce a distinction between `TestcaseEvaluationStatus`, `TestcaseEvaluationResult` and `SolutionCheckResult`. The first describes the status of a solution during and after evaluation, the second describes the result of a solution *after* evaluation thus it's a strict subset of the first, and the last describe a solution check.
We define a partial order on `TestcaseEvaluationResult` based on the corresponding scoring.
Each `SolutionCheckResult` is described by:
* a long name (`SolutionCheckResult::as_str`)
* a short name (`SolutionCheckResult::as_compact_str`)
* a set of `TestcaseEvaluationResult` (`SolutionCheckResult::minimals`)
We say that `outcomes: [TestcaseEvaluationResult]` satisfies a `sol_check: SolutionCheckResult` iff there
exists a …
> Improve solution checks

- src/tools/fuzz_checker/checker_header.h
- src/tools/fuzz_checker/fuzzer.cpp
EXIT() needs to be defined in `checker.so`, not in the binary that `dlopen`s it.
> Fix the checker fuzzer.

- task-maker-format/src/ioi/mod.rs
cms and tmr are using different names for `score_types`' values. This PR improves the compatibility of the two programs.
> Support cms names for score_type

- task-maker-format/src/ioi/sanity_checks/task.rs
The sanity check `NoBitsStdCpp` is too vebose, this PR reduce the screen space used by the generated warning.
Before:
```
Warning: bits/stdc++.h included from sol/sol_db.cpp
Note: This won't compile under Clang
sol/sol_db.cpp:1:0
1 | #include <bits/stdc++.h>
^^^^^^^^^^^^^^^^^^^^^^^^
Warning: bits/stdc++.h included from sol/sol_db_2.cpp
Note: This won't compile under Clang
sol/sol_db_2.cpp:1:0
1 | #include <bits/stdc++.h>
^^^^^^^^^^^^^^^^^^^^^^^^
Warning: bits/stdc++.h included from sol/sol_db_qn.cpp
Note: This won't compile under Clang
sol/sol_db_qn.cpp:1:0
1 | #include <bits/stdc++.h>
^^^^^^^^^^^^^^^^^^^^^^^^
Warning: bits/stdc++.h included from sol/sol_db_qn2.cpp
Note: This won't compile under Clang
sol/sol_db_qn2.cpp:1:0
1 | #include <bits/stdc++.h>
^^^^^^^^^^^^^^^^^^^^^^^^
Warning: …
```
> Reduce NoBitsStdCpp verbosity

- task-maker-format/src/ioi/dag/task_type/batch.rs
- task-maker-format/src/ioi/dag/task_type/communication.rs
- task-maker-format/src/ioi/mod.rs
- task-maker-format/src/solution.rs
- task-maker-format/tests/score_manager.rs
Currently a subtask without testcases is scored incorrectly, this will be useful for #208.
> fix empty subtask scoring

- src/context.rs
To improve the reliability of benchmarks it's better to use the number of physical cores in the system.
> Use physical number of cpus

- data/statements/cms-contest.cls
This allows ois task to use the `\limitist` / `\stconstraints` macro.
> merge oisubtaskcounter and subtaskcounter

- task-maker-format/src/ioi/statement/asy.rs
Asymptote 2.87 changed the behavior of the `-o` flag. By not specifying an output file asymptote uses the default `{source}.pdf` filename, and we gain compatibility with the new version while maintaining compatibility with the older ones.
> compatibility with asymptote 2.87

- src/tools/find_bad_case/dag.rs
Fixes `task-maker-tools find-bad-case`, missing tests.
> fixed find_bad_case not working

- Cargo.lock
- Cargo.toml
- task-maker-cache/Cargo.toml
- task-maker-dag/Cargo.toml
- task-maker-diagnostics/Cargo.toml
- task-maker-exec/Cargo.toml
- task-maker-format/Cargo.toml
- task-maker-lang/Cargo.toml
- task-maker-store/Cargo.toml
Dependabot is not able to update a dependency in multiple crates in a single pull requests, leading to conflicting versions. Using workspace dependencies the issue is avoided.
> Using workspace dependencies

- task-maker-format/src/ioi/mod.rs
- task-maker-format/src/ioi/sanity_checks/statement.rs
- task-maker-format/tests/ioi_sanity_checks.rs
> Updated sanity checks for statements

- Cargo.toml
- task-maker-format/src/ioi/format/italian_yaml/cases_gen.rs
- tools/ubuntu/apparmor-task-maker-rust
This commit adds an apparmor configuration file that allows user namespaces for task-maker-rust, un-breaking tmr on newer 'buntus.
Fixes #248
> Make task-maker-rust debian packages work on Ubuntu 23.10+.
