Cargo.lock, src/local.rs, src/opt.rs, task-maker-format/Cargo.toml, task-maker-format/src/ioi/mod.rs, task-maker-format/src/ioi/statement/booklet.rs, task-maker-format/src/lib.rs
Add a `--task-info` option to show information about the current task
=> Add --task-info option

src/local.rs, src/opt.rs, task-maker-dag/src/dag.rs, task-maker-dag/src/execution.rs, task-maker-exec/src/scheduler.rs
This may become useful to implement scheduling of tasks in the server
version of task-maker.
=> Implement DAG-level priority.

Cargo.lock, task-maker-async/Cargo.toml, task-maker-async/src/lib.rs, task-maker-async/src/server.rs, task-maker-async/src/store.rs
The async implementation should be simpler to reason about, allow to
more easily implement some missing features (i.e. streaming of stdout)
and ideally resolve issues due to mixing threads and fork.
=> API for an async implementation of task-maker-rust. 

Cargo.lock, Cargo.toml, task-maker-async/Cargo.toml, task-maker-async/src/error.rs, task-maker-async/src/lib.rs, task-maker-async/src/server.rs, task-maker-async/src/store.rs
Still missing: hash verification, waiting until a fileset is created,
all the File operations.
=> Implement most of the FileSet part of the API.

task-maker-async/src/client.rs, task-maker-async/src/dag.rs, task-maker-async/src/error.rs, task-maker-async/src/server.rs, task-maker-async/src/store.rs
Still missing: checking compatible variants, handling cancellation, checking input is actually a DAG.
=> First implementation of the server.

Cargo.lock, task-maker-async/Cargo.toml, task-maker-async/src/lib.rs, task-maker-async/src/server.rs, task-maker-async/src/store.rs, task-maker-async/src/worker.rs, task-maker-exec/src/detect_exe.rs, task-maker-exec/src/lib.rs
The code should be fundamentally complete.
Also adds a TODO for missing functionality in the server.
Also (in a separate commit) do some cleanup.
=> Implement the async worker.

task-maker-format/src/ui/curses.rs, task-maker-format/src/ui/mod.rs
Fix ui on terminals that don't support RGB colors.
=> Fix ui colors

task-maker-format/src/ioi/format/italian_yaml/mod.rs, task-maker-lang/src/source_file.rs
=> Fix compilation on macOS

task-maker-format/src/ioi/ui_state.rs
I left a bug in #73, this should fix it.
=> Fix bug using WrongAnswer as PartialScore

task-maker-format/src/ioi/curses_ui.rs, task-maker-format/src/ioi/finish_ui.rs, task-maker-format/src/ioi/ui_state.rs, task-maker-format/src/lib.rs, task-maker-format/src/testcase_score_status.rs
=> Use the same criteria for coloring testcases and subtasks

src/tools/find_bad_case/dag.rs, task-maker-format/src/ioi/dag/mod.rs, task-maker-format/src/ioi/format/italian_yaml/gen_gen.rs, task-maker-format/src/ioi/format/italian_yaml/mod.rs, task-maker-format/src/ioi/format/italian_yaml/static_inputs.rs, task-maker-format/src/ioi/mod.rs, task-maker-format/src/ioi/sanity_checks/att.rs, task-maker-format/tests/utils.rs
=> Using subtask 0 for example in att/ for validation

task-maker-lang/src/languages/c.rs, task-maker-lang/src/languages/cpp.rs, task-maker-lang/src/languages/rust.rs
This includes:
- CXX, CXXFLAGS
- CC, CFLAGS
- RUSTUP_HOME
Fixes #86
CC: @veluca93
=> Fallback to CXX if TM_CXX is not set (and similar)

task-maker-format/src/ioi/sanity_checks/mod.rs, task-maker-format/src/ioi/sanity_checks/task.rs
=> SanityCheck to avoid #include <bits/stdc++.h> in .cpp/.cc files

task-maker-format/src/ioi/sanity_checks/att.rs, task-maker-format/src/ioi/sanity_checks/mod.rs, task-maker-format/src/source_file.rs
=> Sanity check: the grader and template in att/ should compile together

task-maker-format/src/ioi/sanity_checks/mod.rs, task-maker-format/src/ioi/sanity_checks/sol.rs
Followup to [https://github.com/edomora97/task-maker-rust/pull/83#discussion_r1038420777](https://github.com/edomora97/task-maker-rust/pull/83#discussion_r1038420777)
=> Sanity check: sol/template.ext should point to att/taskname.ext

task-maker-cache/src/lib.rs, task-maker-cache/src/storage.rs, task-maker-store/src/index.rs
Profiling tmr on a fully cached task shows that `bincode::deserialize_from` and `bincode::serialize_into` take up most of the time (bincode::* highlighted in pink, taking up 65% of the run time):
This can be traced back to `bincode` not buffering reads and writes, so this PR wraps files in a `BufReader/BufWriter` when they are to be used for (de)serialization.
Running on the same task and with the same cache contents, the end result is that `bincode` is reduced to ~4% of the run time:
Testing with a bigger cache shows no signs of slowing down, with tasks that when cached took ~6s before now running in 1s (limited by the 1s polling interval), so this should solve #98. Given that the cache is now fast to fully read into memory (it's only a few megabytes even with a 5GB store containing 3100 …
=> Faster cache

Cargo.lock, task-maker-format/Cargo.toml, task-maker-format/src/ioi/sanity_checks/subtasks.rs
=> Check if all the testcases in a subtask have the same output

data/statements/cms-contest.cls, data/statements/locale/dutch.tex, data/statements/locale/french.tex, data/statements/locale/german.tex
This PR adds French, German and Dutch. It also fixes a small issue when translating `Subtask`.
=> Add more languages

data/statements/cms-contest.cls, data/statements/locale/dutch.tex, data/statements/locale/english.tex, data/statements/locale/french.tex, data/statements/locale/german.tex, data/statements/locale/hungarian.tex, data/statements/locale/italian.tex, data/statements/locale/portuguese.tex, data/statements/locale/spanish.tex
Closes edomora97/task-maker-rust#198
=> Add Hungarian localization

task-maker-format/src/ioi/finish_ui.rs
Handle properly unknown scores on finish_ui instead of printing zeros.
Before:
After:
=> handle unknown score on finish_ui

Cargo.lock, Cargo.toml, src/tools/main.rs, src/tools/mod.rs, src/tools/opt.rs, src/tools/terry_statement.rs, task-maker-format/src/terry/finish_ui.rs, task-maker-format/src/terry/format/mod.rs, task-maker-format/src/terry/mod.rs, task-maker-format/src/terry/sanity_checks/statement.rs, task-maker-format/src/terry/statement/mod.rs
Adding support to prepare terry tasks with subtasks.
=> Support for terry subtasks

rust-toolchain.toml, task-maker-exec/src/execution_unit/sandbox.rs, tests/classic.rs
=> Fix rust compilation
